import { NextRequest, NextResponse } from 'next/server'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/auth'
import { KnowledgeBaseService } from '@/lib/services/knowledge-base'
import { z } from 'zod'

const createArticleSchema = z.object({
  title: z.string().min(1, 'Title is required'),
  content: z.string().min(1, 'Content is required'),
  category: z.string().min(1, 'Category is required'),
  tags: z.array(z.string()),
  visibility: z.enum(['internal', 'public']),
  autoGenerated: z.boolean().optional(),
})

export async function GET(request: NextRequest) {
  try {
    const session = await getServerSession(authOptions)

    if (!session?.user?.orgId) {
      return NextResponse.json(
        { success: false, error: 'Unauthorized' },
        { status: 401 }
      )
    }

    const { searchParams } = new URL(request.url)
    const filters = {
      category: searchParams.get('category') || undefined,
      visibility: searchParams.get('visibility') || undefined,
      isArchived: searchParams.get('isArchived') === 'true' ? true : undefined,
      search: searchParams.get('search') || undefined,
      tags: searchParams.get('tags')?.split(',') || undefined,
    }

    const articles = await KnowledgeBaseService.getArticles(
      session.user.orgId,
      filters
    )

    return NextResponse.json({
      success: true,
      data: articles,
    })
  } catch (error) {
    console.error('Get articles error:', error)
    return NextResponse.json(
      { success: false, error: 'Failed to fetch articles' },
      { status: 500 }
    )
  }
}

export async function POST(request: NextRequest) {
  try {
    const session = await getServerSession(authOptions)

    if (!session?.user?.orgId) {
      return NextResponse.json(
        { success: false, error: 'Unauthorized' },
        { status: 401 }
      )
    }

    const body = await request.json()
    const validatedData = createArticleSchema.parse(body)

    const article = await KnowledgeBaseService.createArticle(
      session.user.orgId,
      validatedData,
      session.user.id
    )

    return NextResponse.json({
      success: true,
      data: article,
      message: 'Article created successfully',
    })
  } catch (error) {
    console.error('Create article error:', error)

    if (error instanceof z.ZodError) {
      return NextResponse.json(
        {
          success: false,
          error: 'Validation error',
          details: error.errors,
        },
        { status: 400 }
      )
    }

    return NextResponse.json(
      { success: false, error: 'Failed to create article' },
      { status: 500 }
    )
  }
}
